# Site information
title: David's Blog
email: david.federman@outlook.com
description: Some guy's programming blog.
baseurl: ""
url: "https://dfederm.com/"

# Site settings
permalink: /:title
markdown: kramdown
paginate: 5
paginate_path: "/:num/"
date_format: "%b %-d, %Y"

disqus:
  shortname: dfederm

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
